swagger: "2.0"

info:
  title: swagger 2.0
  version: 1.0.0
  description: ""
paths:
  /:
    get:
      responses:
        200:
          description: sample response
          schema:
            $ref: '#/definitions/Hoge'
            example:
              id: 1
              nam: "hoge"

#          examples:
#            application/json; charset=utf-8: {"id": 1, "nam": "hoge"}

definitions:
  Hoge:
    type: object
    properties:
      id:
        type: integer
      nam:
        type: string
    example:
      id: 1
      nam: "hoge"


